/**
 * AuditLog — tamper-evident HMAC-chained event log
 * ----------------------------------------------------------------------------
 * Every security-relevant event (URL check, block, report submission, settings
 * change) is appended to a log where each entry's HMAC depends on the PREVIOUS
 * entry's HMAC. That "chain" means:
 *
 *   - If an attacker modifies or deletes ANY past entry, every subsequent
 *     HMAC becomes invalid. Tampering is detectable.
 *   - An attacker can still truncate from the TAIL (that's the fundamental
 *     limit of local tamper-evidence). To close that hole we also keep a
 *     sequence counter and the backend mirrors the log so truncation can
 *     be detected cross-system. That bigger picture is in backend/storage/
 *     audit_log.js.
 *
 * Inspired by the Merkle-chain style used in Certificate Transparency and
 * in Linux's IMA. We use HMAC-SHA-256 (symmetric) because we don't need
 * non-repudiation between users here — just integrity against local tampering.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *  SECURITY NOTES
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *  - The HMAC key is generated by Web Crypto with `extractable: false`.
 *    That means even if a page JS somehow gained access to our storage,
 *    it could NOT exfiltrate the raw key material — only use it.
 *  - We use a monotonically increasing `seq` field so replay/duplicate
 *    attacks are visible.
 *  - Log is capped to 1000 entries; oldest entries are rolled off. We keep
 *    a running "tail HMAC" so even rolled-off entries count towards the
 *    chain anchor.
 */

class AuditLog {
  constructor() {
    this.STORAGE_KEY = 'catphish_audit_log';
    this.KEY_STORAGE = 'catphish_audit_hmac_key';
    this.ANCHOR_KEY  = 'catphish_audit_anchor';   // rolling-tail HMAC of pruned entries
    this.SEQ_KEY     = 'catphish_audit_seq';      // sequence counter (survives pruning)
    this.MAX_ENTRIES = 1000;
    this.hmacKey = null;
  }

  async init() {
    // SECURITY: load or generate the HMAC key. Generated keys are marked
    // NOT extractable so they cannot be exported back out via subtle.crypto.
    try {
      const items = await chrome.storage.local.get([this.KEY_STORAGE]);
      if (items[this.KEY_STORAGE]) {
        // We stored the key as a CryptoKey via structuredClone — chrome.storage
        // can round-trip it. If round-tripping fails (e.g. old browser) we
        // regenerate.
        try {
          this.hmacKey = items[this.KEY_STORAGE];
          // Test: sign a dummy string. If this fails, regenerate.
          await crypto.subtle.sign('HMAC', this.hmacKey, new TextEncoder().encode('ping'));
        } catch (_) {
          this.hmacKey = await this._generateKey();
          await chrome.storage.local.set({ [this.KEY_STORAGE]: this.hmacKey });
        }
      } else {
        this.hmacKey = await this._generateKey();
        await chrome.storage.local.set({ [this.KEY_STORAGE]: this.hmacKey });
      }
    } catch (err) {
      console.error('[AuditLog] init failed, using in-memory key:', err && err.message);
      this.hmacKey = await this._generateKey();  // transient; better than nothing
    }
  }

  async _generateKey() {
    return crypto.subtle.generateKey(
      { name: 'HMAC', hash: 'SHA-256', length: 256 },
      false,                         // SECURITY: NOT extractable
      ['sign', 'verify']
    );
  }

  /**
   * Append an event to the log.
   * @param {object} event  arbitrary JSON-serializable event data
   */
  async append(event) {
    if (!this.hmacKey) await this.init();

    const items = await chrome.storage.local.get([this.STORAGE_KEY, this.ANCHOR_KEY, this.SEQ_KEY]);
    const log = Array.isArray(items[this.STORAGE_KEY]) ? items[this.STORAGE_KEY] : [];
    const prevHmac = log.length ? log[log.length - 1].hmac : (items[this.ANCHOR_KEY] || 'GENESIS');
    const seq = (Number(items[this.SEQ_KEY]) || 0) + 1;

    const entry = {
      seq,
      ts: new Date().toISOString(),
      prevHmac,                                  // link to previous entry
      event: this._sanitizeEvent(event)          // SECURITY: strip functions / prototypes
    };
    entry.hmac = await this._hmac(this._canonical(entry));

    log.push(entry);

    // Roll off old entries once we exceed cap. We FOLD their HMACs into the
    // anchor so the chain remains verifiable from the anchor onward.
    let anchor = items[this.ANCHOR_KEY] || 'GENESIS';
    while (log.length > this.MAX_ENTRIES) {
      const dropped = log.shift();
      anchor = await this._hmac(anchor + '|' + dropped.hmac);
    }

    await chrome.storage.local.set({
      [this.STORAGE_KEY]: log,
      [this.ANCHOR_KEY]: anchor,
      [this.SEQ_KEY]: seq
    });
  }

  /**
   * Read every entry currently stored (not including pruned ones).
   * @returns {Promise<Array<object>>}
   */
  async readAll() {
    const items = await chrome.storage.local.get([this.STORAGE_KEY]);
    return Array.isArray(items[this.STORAGE_KEY]) ? items[this.STORAGE_KEY] : [];
  }

  /**
   * Verify that the HMAC chain is intact.
   * Returns false if ANY entry has been modified/deleted/reordered.
   */
  async verifyChain() {
    const items = await chrome.storage.local.get([this.STORAGE_KEY, this.ANCHOR_KEY]);
    const log = Array.isArray(items[this.STORAGE_KEY]) ? items[this.STORAGE_KEY] : [];
    let prev = items[this.ANCHOR_KEY] || 'GENESIS';

    for (const entry of log) {
      if (entry.prevHmac !== prev) return false;          // broken link
      // Recompute HMAC over the entry (minus hmac field)
      const { hmac, ...rest } = entry;
      const expected = await this._hmac(this._canonical(rest));
      if (expected !== hmac) return false;                // entry modified
      prev = hmac;
    }
    return true;
  }

  // ---- internals ----------------------------------------------------------

  /** Deterministic JSON — keys sorted — so HMACs are stable. */
  _canonical(obj) {
    return JSON.stringify(obj, Object.keys(obj).sort());
  }

  async _hmac(str) {
    const buf = new TextEncoder().encode(str);
    const sig = await crypto.subtle.sign('HMAC', this.hmacKey, buf);
    // hex encode
    const bytes = new Uint8Array(sig);
    let hex = '';
    for (let i = 0; i < bytes.length; i++) hex += bytes[i].toString(16).padStart(2, '0');
    return hex;
  }

  /**
   * Strip functions, symbols, and other non-JSON-safe values from an event.
   * SECURITY: This defends against prototype pollution / unexpected getters
   * that could otherwise smuggle code through `JSON.stringify`.
   */
  _sanitizeEvent(event) {
    if (!event || typeof event !== 'object') return {};
    const clean = {};
    for (const key of Object.keys(event)) {
      const v = event[key];
      if (v == null) continue;
      if (typeof v === 'function' || typeof v === 'symbol') continue;
      if (typeof v === 'object') {
        clean[key] = this._sanitizeEvent(v);
      } else {
        // String-coerce and cap
        clean[key] = String(v).slice(0, 500);
      }
    }
    return clean;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = AuditLog;
}
